log4j.rootCategory=INFO, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
log4j.logger.org.apache.zookeeper=ERROR
log4j.logger.org.apache.hadoop.hdfs.distributedavatarfilesystem=ERROR
log4j.logger.org.apache.hadoop.util.NativeCodeLoader=ERROR
#log4j.logger.org.apache.hadoop.yarn.util.ProcfsBasedProcessTree=ERROR
log4j.logger.org.apache.hadoop.io.retry.RetryInvocationHandler=WARN
log4j.logger.org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl=WARN

# Settings to quiet third party logs that are too verbose
